### ISSUE TITLE
Ошибка/Error - ajax-get-geo-objects-placemark

### ISSUE THREAD

**Issue by AlexanderBardin** [genkosta/django-editor-ymaps#3]
При открытии карты на редактирование не появляется меню редактора, при этом в браузере ошибка - https://s.mail.ru/AiJn/SKn2AaAto
запрос не проходит
```
http://127.0.0.1:8000/djeym/ajax-get-geo-objects-placemark/?map_id=3&offset=0
```

лог django
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\djeym\views.py", line 193, in dispatch
    return super(AjaxGetGeoObjectsPlacemark, self).dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\djeym\views.py", line 184, in get
    LIMIT 1000 OFFSET %s""", [map_id, offset])
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: TRUE
[25/Mar/2019 11:08:47] "GET /djeym/ajax-get-geo-objects-placemark/?map_id=3&offset=0 HTTP/1.1" 500 23847

```
в таблице djeym_placemark данные есть
контакты
почта - general_als@mail.ru 
телеграмм - @Bardin_A_A

**Comment by genkosta** [comment]
Благодарю за сообщение.
Такую ошибку пока не получал. Судя по первому пункту из https://cloud.mail.ru/public/AiJn/SKn2AaAto, не смог подгрузится бейджик по адресу - https://pepy.tech/badge/django-editor-ymaps.

Я убрал все бейджи и обновился.
Сделайте обновления до последней версии и проверьте результат.

контакты:
почта - genkosta43@gmail.com
телеграмм - @genkosta

**Comment by AlexanderBardin** [comment]
Похоже проблема не только в этом - https://s.mail.ru/dB9e/2ZZ71PWkK
Опять же лог django
```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\djeym\views.py", line 193, in dispatch
    return super(AjaxGetGeoObjectsPlacemark, self).dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\djeym\views.py", line 184, in get
    LIMIT 1000 OFFSET %s""", [map_id, offset])
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: TRUE
[27/Mar/2019 09:48:24] "GET /djeym/ajax-get-geo-objects-placemark/?map_id=3&offset=0 HTTP/1.1" 500 23989

```

меня вот это смущает
```
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: TRUE

```
чтобы не гадать, вот проект - https://github.com/AlexanderBardin/ymapsPrj
базу с данными тоже приложил (может дело в ней)
логин - admin
пароль - 1
Делал все по инструкции, возможно что-то упустил.

**Comment by genkosta** [comment]
Причиной оказались прямые запросы к базе. Теперь SQLite3 полностью поддерживается. 

Проект обновился до новой версии.

Если для проверки используете кастомную команды `python manage.py addmarker`, что бы добавить маркеры в базу, рекомендую для карты установить масштаб = 3. При большом зуме, может, не один маркер, не попасть на данную площадь карты.

p.s. Локально запустил Ваш проект. Маркеры на карту грузятся нормально.

**Comment by AlexanderBardin** [comment]
Да, карта загрузилась.

**Comment by genkosta** [comment]
OK
